# Generated by Django 4.0.6 on 2022-08-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dumy',
        ),
        migrations.DeleteModel(
            name='User_history',
        ),
    ]
